title: "NOCTUA / Urban Lens"
description: "Night & street photography from the city's dark corners."
baseurl: ""
url: "https://aalvesphoto.github.io"   # ‚Üê change to your GitHub username

# Build
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Plugins (all GitHub Pages safe)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  galleries:
    output: true
    permalink: /galleries/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: galleries
    values:
      layout: gallery
